version: "3.9"
services:
  backend:
    build: ./backend
    container_name: devops-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://root:example@database:27017/devopsstudy?authSource=admin
      - JWT_SECRET=supersecretjwtkey
      - PORT=5000
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: devops-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  database:
    build: ./database
    container_name: devops-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  mongo-data:
